# Generated by Django 2.1.4 on 2019-01-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190129_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='posts',
            name='username',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
